### ISSUE TITLE
Oi :-)

### ISSUE THREAD

**Issue by fxcosta** [mateussousap/HTML5_CSS3_JS#1]
Esse repo vai ter algumas dicas legais de HTML5? Estou acompanhando...

**Comment by mateussousap** [comment]
Olá fxcosta, criei esse repositório apenas para compartilhar os códigos de um curso que estou fazendo. Observando as aulas e tentando melhorar, conforme meu conhecimento permita. Aguardo seus comentários e sugestões. Abraço.

**Comment by fxcosta** [comment]
Me segue também e vou fechar a issue, hehe. Quando tiver algo eu dou fork e dou um PR (pull request), vc recebe a solicitação, analisa e aí faz a mesclagem com o seu repo original, hehe.

**Comment by mateussousap** [comment]
Seguindo =)
